const cfg=window.PENSION_CONFIG||{};
const $=s=>document.querySelector(s);
let client=null, rows=[];
function msg(text,bad=false){const el=$('#loginMsg');el.textContent=text;el.classList.remove('hidden');el.classList.toggle('ok',!bad)}
function money(n){return new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:0}).format(Number(n||0))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function statusLabel(s){return ({new:'חדש',in_review:'בטיפול',waiting_data:'ממתין לנתונים',report_uploaded:'דוח הועלה',analyzed:'נותח',ready:'תוצאה מוכנה',sent:'נשלח ללקוח',viewed:'נצפה',callback_requested:'ביקש שיחה',completed:'הושלם',closed:'נסגר'})[s]||s}
function cleanCell(v){return String(v??'').trim()}
function numCell(v){if(typeof v==='number')return Number.isFinite(v)?v:0;const s=cleanCell(v).replace(/,/g,'').replace(/[^0-9.\-]/g,'');const n=Number(s);return Number.isFinite(n)?n:0}
function annualizePremium(amount,type){const t=cleanCell(type);if(/חודש/.test(t))return amount*12;if(/רבע/.test(t))return amount*4;return amount}
function parseStartYear(period){const m=cleanCell(period).match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?Number(m[3]):null}
function insuranceBucket(main){const v=cleanCell(main);if(v.includes('רכב')||v.includes('דירה'))return'general';if(v.includes('בריאות')||v.includes('סיעודי')||v.includes('כתב שירות')||v.includes('תאונות'))return'health';if(v.includes('חיים')||v.includes('כושר עבודה'))return'life';return'other'}
function maskPolicy(v){const s=cleanCell(v);if(!s)return'ללא מספר';return s.length<=4?s:`••••${s.slice(-4)}`}
async function parseInsuranceWorkbook(file){
  if(!window.XLSX)throw new Error('Excel parser unavailable');
  const buf=await file.arrayBuffer();const book=XLSX.read(buf,{type:'array',raw:false});const ws=book.Sheets[book.SheetNames[0]];const grid=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});
  const headerIndex=grid.findIndex(row=>row.some(v=>cleanCell(v)==='תעודת זהות')&&row.some(v=>cleanCell(v)==='ענף ראשי')&&row.some(v=>cleanCell(v).includes('פרמיה')));
  if(headerIndex<0)throw new Error('לא נמצאו כותרות מוכרות של דוח הר הביטוח');
  const headers=grid[headerIndex].map(cleanCell);const idx=(name,partial=false)=>headers.findIndex(h=>partial?h.includes(name):h===name);
  const c={main:idx('ענף ראשי'),sub:idx('ענף (משני)'),product:idx('סוג מוצר'),company:idx('חברה'),period:idx('תקופת ביטוח'),details:idx('פרטים נוספים'),premium:idx('פרמיה',true),premiumType:idx('סוג פרמיה'),policy:idx('מספר פוליסה')};
  if([c.main,c.sub,c.company,c.premium,c.premiumType].some(x=>x<0))throw new Error('חסרות עמודות נדרשות בדוח');
  const records=[];
  for(const row of grid.slice(headerIndex+1)){const main=cleanCell(row[c.main]);if(!main||main.startsWith('תחום -'))continue;const amount=numCell(row[c.premium]);if(!cleanCell(row[c.company])&&!amount)continue;records.push({main,sub:cleanCell(row[c.sub]),product:cleanCell(row[c.product]),company:cleanCell(row[c.company]),period:cleanCell(row[c.period]),details:cleanCell(row[c.details]),premium:amount,premiumType:cleanCell(row[c.premiumType]),policy:cleanCell(row[c.policy]),annual:annualizePremium(amount,row[c.premiumType])})}
  if(!records.length)throw new Error('לא נמצאו רשומות ביטוח בדוח');
  const sum=arr=>arr.reduce((a,b)=>a+b,0);const annualTotal=sum(records.map(r=>r.annual));const categories={general:0,health:0,life:0,other:0};records.forEach(r=>categories[insuranceBucket(r.main)]+=r.annual);
  const policies=new Map();records.forEach(r=>{const key=r.policy||`${r.company}|${r.main}|${r.sub}`;if(!policies.has(key))policies.set(key,{policyMasked:maskPolicy(r.policy),company:r.company,main:r.main,annual:0,coverages:new Set(),period:r.period,startYear:parseStartYear(r.period)});const p=policies.get(key);p.annual+=r.annual;p.coverages.add(r.sub||r.product);if(!p.startYear)p.startYear=parseStartYear(r.period)});
  const policyList=[...policies.values()].map(p=>({...p,coverages:[...p.coverages].filter(Boolean)})).sort((a,b)=>b.annual-a.annual);
  const mandatoryPolicies=new Set(records.filter(r=>r.sub.includes('רכב חובה')).map(r=>r.policy||r.company));const comprehensivePolicies=new Set(records.filter(r=>r.sub.includes('ביטוח מקיף')&&r.product==='פוליסת ביטוח').map(r=>r.policy||r.company));
  const lifeAnnual=sum(records.filter(r=>r.main.includes('ביטוח חיים')).map(r=>r.annual));const nursingRecords=records.filter(r=>r.main.includes('סיעודי'));const healthPolicy=policyList.find(p=>p.main.includes('בריאות')&&p.coverages.length>=3);const oldest=policyList.filter(p=>p.startYear).sort((a,b)=>a.startYear-b.startYear)[0];const zeroCostRiders=records.filter(r=>r.premium===0).length;
  const insights=[{level:'info',title:'עלות הביטוחים בתיק',text:`לפי הדוח, סך הפרמיות הוא כ-${money(annualTotal)} לשנה, שהם כ-${money(annualTotal/12)} לחודש בממוצע.`}];
  if(lifeAnnual>0)insights.push({level:'warn',title:'ביטוח החיים הוא רכיב משמעותי בעלות',text:`ביטוח החיים עולה כ-${money(lifeAnnual/12)} לחודש (${money(lifeAnnual)} לשנה). לפני שינוי חשוב לבדוק סכום ביטוח, צורך משפחתי ומצב בריאותי.`});
  if(nursingRecords.length){const nursingAnnual=sum(nursingRecords.map(r=>r.annual));const year=Math.min(...nursingRecords.map(r=>parseStartYear(r.period)||9999));insights.push({level:'warn',title:'פוליסת סיעוד ותיקה דורשת זהירות',text:`נמצאה פוליסת סיעוד בעלות של כ-${money(nursingAnnual/12)} לחודש${year<9999?`, שמתחילה בשנת ${year}`:''}. אין לבטל או להחליף לפני בדיקה מקצועית.`})}
  if(mandatoryPolicies.size>1||comprehensivePolicies.size>1)insights.push({level:'warn',title:'מספר פוליסות רכב פעילות',text:`בדוח נמצאו ${mandatoryPolicies.size} פוליסות חובה ו-${comprehensivePolicies.size} פוליסות מקיף. אם מדובר במספר כלי רכב זה עשוי להיות תקין; אם מדובר באותו רכב, כדאי לבדוק חפיפה.`});
  if(healthPolicy)insights.push({level:'good',title:'כיסויי בריאות מרוכזים בפוליסה מרכזית',text:`בפוליסה ${healthPolicy.policyMasked} אצל ${healthPolicy.company} מרוכזים ${healthPolicy.coverages.length} כיסויים/שירותים.`});
  if(oldest&&oldest.startYear&&oldest.startYear<=new Date().getFullYear()-10)insights.push({level:'info',title:'נמצאה פוליסה ותיקה',text:`הפוליסה הוותיקה ביותר בדוח מתחילה בשנת ${oldest.startYear}. לפני שינוי כדאי לבדוק תנאים, החרגות וזכויות שנצברו.`});
  if(zeroCostRiders)insights.push({level:'good',title:'כתבי שירות ללא פרמיה נפרדת',text:`נמצאו ${zeroCostRiders} רכיבים שמופיעים בדוח בעלות 0 ₪. הם עשויים להיות כלולים במסגרת פוליסה אחרת.`});
  return {rowsCount:records.length,policyCount:policies.size,annualTotal,monthlyAverage:annualTotal/12,categories,policyList,insights,mandatoryCount:mandatoryPolicies.size,comprehensiveCount:comprehensivePolicies.size,lifeAnnual,zeroCostRiders};
}
function token(){const a=new Uint8Array(24);crypto.getRandomValues(a);return Array.from(a,b=>b.toString(16).padStart(2,'0')).join('')}
function resultUrl(t){return new URL(`result.html?t=${encodeURIComponent(t)}`,location.href).href}
async function init(){
  if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){msg('יש להשלים config.js לפני שימוש במערכת הניהול.',true);return}
  client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);
  const {data:{session}}=await client.auth.getSession();if(session)showAdmin();
}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);const {error}=await client.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)return msg('הכניסה נכשלה. בדוק אימייל, סיסמה והרשאת Admin.',true);showAdmin()});
async function showAdmin(){$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');$('#logoutBtn').classList.remove('hidden');await loadRows()}
async function loadRows(){const {data,error}=await client.from('check_requests').select('*').order('created_at',{ascending:false}).limit(200);if(error){alert('לא ניתן לטעון בקשות. ודא שהרצת את migration-v9-results.sql ושהמשתמש מוגדר ב-admin_users.');return}rows=data||[];$('#requestsBody').innerHTML=rows.length?rows.map(r=>`<tr><td>${new Date(r.created_at).toLocaleString('he-IL')}</td><td>${esc(r.full_name)}</td><td>${esc(r.phone||'—')}</td><td>${esc(r.email||'—')}</td><td><span class="status-chip ${r.status==='callback_requested'?'status-hot':''}">${statusLabel(r.status)}</span></td><td><button class="secondary" data-id="${r.id}">פתח</button></td></tr>`).join(''):'<tr><td colspan="6">אין בקשות עדיין</td></tr>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openDetail(b.dataset.id))}
function openDetail(id){
 const r=rows.find(x=>x.id===id);if(!r)return;const p=r.pension_data||{};const hasReport=Boolean(r.insurance_data);const url=r.result_token?resultUrl(r.result_token):'';
 $('#detailContent').innerHTML=`
 <div class="admin-detail"><div><small>שם</small><strong>${esc(r.full_name)}</strong></div><div><small>ת״ז</small><strong>${esc(r.id_number)}</strong></div><div><small>תאריך הנפקה</small><strong>${esc(r.id_issue_date)}</strong></div><div><small>טלפון</small><strong>${esc(r.phone||'—')}</strong></div><div><small>אימייל</small><strong>${esc(r.email||'—')}</strong></div><div><small>גיל / שכר</small><strong>${esc(r.age||'—')} · ${r.salary?money(r.salary):'—'}</strong></div><div><small>יתרת פנסיה</small><strong>${p.pensionBalance!==undefined?money(p.pensionBalance):'טרם הוזן'}</strong></div><div><small>חתימה</small><strong>${r.signature_path?'נשמרה באופן פרטי':'לא נמצאה'}</strong><div id="signatureAction"></div></div></div>
 <section class="admin-flow-card"><div class="admin-flow-head"><div><span class="eyebrow">שלב 1</span><h3>העלאת דוח Excel</h3></div><span class="status-chip">${hasReport?'דוח קיים':'ממתין לדוח'}</span></div><p class="muted">לאחר שהפקת את דוח הר הביטוח, העלה אותו כאן. הניתוח מתבצע בדפדפן והסיכום נשמר בבקשה.</p><div class="admin-upload-row"><input id="reportFile" type="file" accept=".xlsx,.xls"><button class="primary" id="uploadReportBtn">העלה ונתח</button></div><div id="reportMsg" class="backend-status ${hasReport?'ok':'hidden'}">${hasReport?`נותח: ${esc(r.report_filename||'דוח Excel')} · ${money(r.insurance_data.annualTotal)} לשנה · ${r.insurance_data.policyCount||0} פוליסות`:''}</div></section>
 <section class="admin-flow-card"><div class="admin-flow-head"><div><span class="eyebrow">שלב 2</span><h3>קישור תוצאה ללקוח</h3></div><span class="status-chip">${r.result_token?'קישור נוצר':'טרם נוצר'}</span></div>${hasReport?`<p class="muted">כשאתה מרוצה מהניתוח, צור קישור אישי. הקישור פועל כקישור סודי ומוגבל ל-30 יום.</p><div class="admin-actions"><button class="primary" id="readyBtn">${r.result_token?'רענן תוקף קישור':'סמן כתוצאה מוכנה וצור קישור'}</button>${r.result_token?'<button class="secondary" id="copyLinkBtn">העתק קישור</button><a class="secondary" target="_blank" rel="noopener" href="'+esc(url)+'">פתח תוצאה</a>':''}</div>${r.result_token?`<div class="result-link-box">${esc(url)}</div>`:''}`:'<p class="muted">יש להעלות דוח לפני יצירת קישור.</p>'}</section>
 ${r.result_token?`<section class="admin-flow-card"><div class="admin-flow-head"><div><span class="eyebrow">שלב 3</span><h3>שליחה ומעקב</h3></div><span class="status-chip ${r.callback_requested_at?'status-hot':''}">${r.callback_requested_at?'הלקוח ביקש שיחה':statusLabel(r.status)}</span></div><p class="muted">שלח את הקישור ידנית ב-WhatsApp או במייל. לאחר השליחה סמן אותו כ"נשלח".</p><div class="admin-actions"><button class="secondary" id="markSentBtn">סמן כנשלח ללקוח</button></div>${r.result_viewed_at?`<p class="admin-event">✓ נצפה: ${new Date(r.result_viewed_at).toLocaleString('he-IL')}</p>`:''}${r.callback_requested_at?`<p class="admin-event hot">🔥 ביקש שיחה: ${new Date(r.callback_requested_at).toLocaleString('he-IL')}</p>`:''}</section>`:''}
 <h3 style="margin-top:20px">סטטוס ידני</h3><div class="admin-actions"><select id="statusSelect"><option value="new">חדש</option><option value="in_review">בטיפול</option><option value="waiting_data">ממתין לנתונים</option><option value="report_uploaded">דוח הועלה</option><option value="analyzed">נותח</option><option value="ready">תוצאה מוכנה</option><option value="sent">נשלח ללקוח</option><option value="viewed">נצפה</option><option value="callback_requested">ביקש שיחה</option><option value="completed">הושלם</option><option value="closed">נסגר</option></select><button class="primary" id="saveStatus">שמור סטטוס</button></div>`;
 if(r.signature_path){client.storage.from('signatures').createSignedUrl(r.signature_path,300).then(({data})=>{if(data?.signedUrl)$('#signatureAction').innerHTML=`<a class="secondary" style="display:inline-flex;margin-top:8px" target="_blank" rel="noopener" href="${data.signedUrl}">צפה בחתימה</a>`})}
 $('#statusSelect').value=r.status;
 $('#uploadReportBtn')?.addEventListener('click',async()=>{const file=$('#reportFile').files?.[0];if(!file)return alert('בחר קובץ Excel');const btn=$('#uploadReportBtn');btn.disabled=true;btn.textContent='מנתח…';try{const analysis=await parseInsuranceWorkbook(file);const {error}=await client.from('check_requests').update({insurance_data:analysis,report_filename:file.name,status:'analyzed',updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;r.insurance_data=analysis;r.report_filename=file.name;r.status='analyzed';$('#reportMsg').classList.remove('hidden');$('#reportMsg').classList.add('ok');$('#reportMsg').textContent=`הדוח נותח בהצלחה: ${money(analysis.annualTotal)} לשנה · ${analysis.policyCount} פוליסות`;setTimeout(()=>openDetail(id),450)}catch(e){console.error(e);alert('לא הצלחתי לנתח את הקובץ: '+(e.message||'שגיאה'))}finally{btn.disabled=false;btn.textContent='העלה ונתח'}});
 $('#readyBtn')?.addEventListener('click',async()=>{const t=r.result_token||token();const exp=new Date(Date.now()+30*24*3600*1000).toISOString();const {error}=await client.from('check_requests').update({result_token:t,result_ready_at:new Date().toISOString(),result_expires_at:exp,status:'ready',updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert('יצירת הקישור נכשלה');r.result_token=t;r.result_expires_at=exp;r.status='ready';openDetail(id)});
 $('#copyLinkBtn')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(resultUrl(r.result_token));alert('הקישור הועתק')});
 $('#markSentBtn')?.addEventListener('click',async()=>{const now=new Date().toISOString();const {error}=await client.from('check_requests').update({result_sent_at:now,status:'sent',updated_at:now}).eq('id',id);if(error)return alert('העדכון נכשל');r.result_sent_at=now;r.status='sent';openDetail(id)});
 $('#saveStatus').onclick=async()=>{const status=$('#statusSelect').value;const {error}=await client.from('check_requests').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert('שמירת הסטטוס נכשלה');r.status=status;$('#detailModal').classList.remove('show');loadRows()};
 $('#detailModal').classList.add('show');
}
$('#closeModal').onclick=()=>$('#detailModal').classList.remove('show');$('#detailModal').onclick=e=>{if(e.target.id==='detailModal')e.currentTarget.classList.remove('show')};$('#refreshBtn').onclick=loadRows;$('#logoutBtn').onclick=async()=>{await client.auth.signOut();location.reload()};init();
